### ISSUE TITLE
Error saving

### ISSUE THREAD

**Issue by HysteriaRP** [grzybeek/YMTEditor#10]
![Screenshot (233)](https://user-images.githubusercontent.com/87357750/164122234-fde0586a-94a8-40f2-ac63-19996c8f1a22.png)
It wont let me save my YMT edits anymore

**Comment by HysteriaRP** [comment]
I can however save it as an XML, just not a YMT

**Comment by HysteriaRP** [comment]
When I close out of it, then tried to open my YMT, it shuts down the whole YMT Editor???

**Comment by HysteriaRP** [comment]
[mp_m_freemode_01_reclothed.zip](https://github.com/grzybeek/YMTEditor/files/8517340/mp_m_freemode_01_reclothed.zip)
keeps crashing and closing YMT Editor when trying to open

**Comment by grzybeek** [comment]
Hey, seems like your .ymt got somehow corrupted. How did you generate it?
Also you have more than 255 drawables in JBIB category, probably that's why you couldn't save it to .ymt

**Comment by HysteriaRP** [comment]
so we cant go over 255?

**Comment by grzybeek** [comment]
Probably you can't, I would need to test it more to be sure

**Comment by HysteriaRP** [comment]
ok ty!

**Comment by HysteriaRP** [comment]
I was curious because Ive seen clothing in the 500s in cities before
