### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by gamergamemail** [grzybeek/YMTEditor#11]
Can I name my ydd and ytd files to 0,1,2,3,4 instead of jbib_000_u_ydd, jbib_diff_000_a_uni.ytd

**Comment by grzybeek** [comment]
YMTEditor is just EDITOR for .ymt files, if you want to setup your addon clothing, you have to name your files properly for them to work. So no, you can't name them "0,1,2,3,4" instead of "jbib_000_u.ydd". Also github issues is not a place for questions, you can ask them anywhere else tho :P

**Comment by gamergamemail** [comment]
> YMTEditor is just EDITOR for .ymt files, if you want to setup your addon clothing, you have to name your files properly for them to work. So no, you can't name them "0,1,2,3,4" instead of "jbib_000_u.ydd". Also github issues is not a place for questions, you can ask them anywhere else tho :P

Sorry.
