### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by termanator1128** [grzybeek/YMTEditor#14]
When importing a YMT or XML. The ExpressionsMods first value is set to 1 instead of -1 (if set)

**Comment by grzybeek** [comment]
Hey, please send me .ymt that can replicate your issue (discord: grzybeek#9100)

**Comment by termanator1128** [comment]
Here you go
[ymt files.zip](https://github.com/grzybeek/YMTEditor/files/9425315/ymt.files.zip)

**Comment by grzybeek** [comment]
Should be fixed in 1.3.2, try new version please
https://github.com/grzybeek/YMTEditor/releases/tag/v1.3.2

**Comment by termanator1128** [comment]
The issue has been fixed.
