### ISSUE TITLE
Missing textures with "corrupted" YMT

### ISSUE THREAD

**Issue by MarcT** [grzybeek/YMTEditor#16]
This has happened to me twice. The first time I stumbled across the solution by starting over from scratch making a DLC and did not have a backup of the old YMT to compare with. 
The first time it happened it was to a baseball cap that had a logo texture. The second time it happened to some glasses that have a glass/plastic layer.
This was the broken hat.
![image](https://user-images.githubusercontent.com/109933/200091661-553c87db-ac0b-4a7a-bbd2-b48760e43124.png)
This was the working one. Both of them were the same model/texture combinations.
![image](https://user-images.githubusercontent.com/109933/200091682-3e1ef500-5336-4851-818d-4520a75bc266.png)
A more obvious one is this.
![image](https://user-images.githubusercontent.com/109933/200091741-86d0121f-055b-4067-95c1-4f376a82442d.png)
And here it is working. This is the same model after removing and recreating the prop eyes section.
![image](https://user-images.githubusercontent.com/109933/200091804-7b03d295-f6cc-4693-ab3b-3de06df2e0ad.png)
According to this comparison of the XMLs from the broken (left) and working(right) YMT files, you can see the propid numbers being incorrect. I am not sure how this happened, because in the YMTEditor itself the eye section started at 0.
![image](https://user-images.githubusercontent.com/109933/200091960-a38fba28-ba74-4ab0-a844-0290b6e29486.png)
![image](https://user-images.githubusercontent.com/109933/200092014-dd123758-fd6d-4cb8-8bbc-4bf7913dafff.png)

**Comment by grzybeek** [comment]
Should be fixed in 1.4!
