### ISSUE TITLE
Male/Female_Heist YMTs are missing their Prop Data

### ISSUE THREAD

**Issue by MarcT** [grzybeek/YMTEditor#19]
In reviewing the YMTs I found that the heist YMTs are "missing" the Prop items. If you load the 2 heist YMTs into YMT Editor, the slots are created where the prop items should live, but no prop items are created.
If you open the YMT using Codewalker you can see the prop items do exist.

**Comment by grzybeek** [comment]
thanks, idk how I missed it before
fixed in https://github.com/grzybeek/YMTEditor/commit/1923305d3f7544e1af93840a78f6b5aa5ae268dd

New release available here https://github.com/grzybeek/YMTEditor/releases/tag/v1.4.1
