### ISSUE TITLE
Unexpected crash.

### ISSUE THREAD

**Issue by YisusOnDev** [grzybeek/YMTEditor#2]
Okey so i'm trying to add custom "task s" but when i try to test in game i got this crash.

![image](https://user-images.githubusercontent.com/52821987/124474676-1cf19680-dda1-11eb-88a8-3c42c7c05afb.png)

Any suggestions?

**Comment by grzybeek** [comment]
@YisusOnDev That's not related to YMTEditor i guess, probably your model/texture is somehow broken(?)

**Comment by YisusOnDev** [comment]
Not broken, if i stream it on mp_freemode (replaceing) or with gtautil addon method it does work.

**Comment by grzybeek** [comment]
@YisusOnDev well, i've never had such crash and can't help you further without any files - send them to me on discord grzybeek#9100
