### ISSUE TITLE
Crash while trying to fix add-on high heels.

### ISSUE THREAD

**Issue by YisusOnDev** [grzybeek/YMTEditor#3]
When I modify FEMALE hash_07AE529 5th parameter in order to make female high heel feet to work it crash when i switch to male and switch feets.

**Comment by grzybeek** [comment]
How many .ymt’s do you have? And which game version your server is running? Maybe you are hitting [this](https://forum.cfx.re/t/how-to-create-addon-heels-or-hide-hair-with-addon-hat/4209989/9) limit?

Also read posts in that topic, few people had crashes and they redo it and it stopped, creaturemetadata file is very unknown and it might crash, maybe i'm generating it wrongly

**Comment by YisusOnDev** [comment]
Ok, nevermind, seems like i update artifacs and it stopped crashing.
I'm using only 1 addon so 2 ymt (female and male) 
b2372
