### ISSUE TITLE
[Feature Request] Selecting a folder and auto generating YMT

### ISSUE THREAD

**Issue by sangyoo91** [grzybeek/YMTEditor#5]
It would be awesome to select a folder, and given the ydd and ytds are named correctly,  the YMT structure is auto generated based on that.

It's just a thought and would be very convenient :D

**Comment by grzybeek** [comment]
There is exactly [alttool](https://github.com/DurtyFree/durty-cloth-tool) which does what you said, it will be updated soon with _u and _r working correctly.
I don't see reason to implement same thing, my tool is only to edit .ymt file, so you don't have to re-generate your whole resource with alttool each time adding only one more clothing.

I have an idea to implement at least "add multiple", so you have to choose only which component, how many drawables and how many each has textures and then it will add automatically all of these, probably much faster than clicking buttons multiple times.

**Comment by sangyoo91** [comment]
That is a fair point :D I look forward to the update
