### ISSUE TITLE
Easily add custom number of models

### ISSUE THREAD

**Issue by HonzaVu** [grzybeek/YMTEditor#7]
Add an option where we can add multiple models at once and not clicking add one by one and then 20 ytd's one by one (after doing it with over 300 clothes i got almost insane). How many models and how many textures and then it will add automatically all of these. Would be lit if you add that

**Comment by grzybeek** [comment]
Yeah, I've been thinking about it too and mentioned it [here](https://github.com/grzybeek/YMTEditor/issues/5), it will be added but not sure when. I don't have much time for now, i'll try to find some time in 1-2 weeks hopefully.

**Comment by grzybeek** [comment]
Probably around january I'll be adding it

**Comment by BTNGaming** [comment]
Any update on this Grzy? If not, I'd do it for you and send a pull request, but I'm an idiot, not sure how to "build" this, and when I try it gives me some codewalker error

**Comment by grzybeek** [comment]
Will be available in 1.4 version, sorry it takes so long, hard to find motivation and time to do this. I have like 70% already done, just have to finish it.

**Comment by grzybeek** [comment]
Finally added with 1.4 version!
