### ISSUE TITLE
cant save a ymt file error.

### ISSUE THREAD

**Issue by hAKIZOR** [grzybeek/YMTEditor#8]
After i save my ymt file appear a popup error. I attach my ymt file.
When i try to open a saved ymt file there is a crash. Im just trying to remove "berd" component
[ymt.zip](https://github.com/grzybeek/YMTEditor/files/7135677/ymt.zip)

**Comment by hAKIZOR** [comment]
update: when i try to save it in xml it works but i need ymt file .

**Comment by grzybeek** [comment]
Hey, thanks for reporting it! I've forgot to calculate one field and it was too big in terms of .ymt structure. I'll try to work on an update for YMTEditor in next days, so it will be fixed in new version.

As a workaround for now you can save it to .xml -> edit .xml and change line 29712 (`numAvailProps value="X"`) value to some smaller value than 255 -> import .xml into codewalker rpf explorer, it will create .ymt from your .xml

**Comment by hAKIZOR** [comment]
Ok thanks i'll try wait a moment :D

**Comment by hAKIZOR** [comment]
> Hey, thanks for reporting it! I've forgot to calculate one field and it was too big in terms of .ymt structure. I'll try to work on an update for YMTEditor in next days, so it will be fixed in new version.
> 
> As a workaround for now you can save it to .xml -> edit .xml and change line 29712 (`numAvailProps value="X"`) value to some smaller value than 255 -> import .xml into codewalker rpf explorer, it will create .ymt from your .xml

after codewalker create .ymt file should i reset the `numAvailProps value="X" ? it was 275 and i change it to 254

**Comment by grzybeek** [comment]
> after codewalker create .ymt file should i reset the `numAvailProps value="X" ? it was 275 and i change it to 254

No, you can keep it as 254

**Comment by hAKIZOR** [comment]
ok i tryed to restart my server and i was trasparent and after 2 min i crash.
I try to explain my problem, maybe im make a mistake.
I downloaded a pack of EUP. There are a lot of mask different between Male and Female... So the mask 8 of male is different from the mask 8 of female. To solve this problem i've deleted all "berd" eup from the stream folder. Now the "custom mask" are removed from the clothes shop but their number are still in the clothes shop without any mask. Thats why i want to remove the Berd Component from the ymt file, i'm right?

**Comment by grzybeek** [comment]
Yes, you have to remove berd from .ymt if you don't want any new numbers.
If you are crashing after loading model it might be related to this limit of .ymt's -> https://forum.cfx.re/t/setplayermodel-crash-when-you-have-too-much-ymts-assigned-to-a-freemode-ped-model/1934063

**Comment by hAKIZOR** [comment]
> Yes, you have to remove berd from .ymt if you don't want any new numbers.
> If you are crashing after loading model it might be related to this limit of .ymt's -> https://forum.cfx.re/t/setplayermodel-crash-when-you-have-too-much-ymts-assigned-to-a-freemode-ped-model/1934063

I think its not a limit problem cause if i dont edit ymt all works good (with more number in mask clothes shop).
And if i removing Berd component im decreasing the ymt file.

**Comment by hAKIZOR** [comment]
ok i crash with B2189 error... but how is possible? i've deleted all berd component so im just decreasing it :(

**Comment by grzybeek** [comment]
It means total amount of your .ymt's on your server, on 2189 version it's 6 maximum .ymt's for male and 6 for female.

**Comment by hAKIZOR** [comment]
i've just 2 ymt file... 1 for male and 1 for female

**Comment by hAKIZOR** [comment]
@grzybeek don't know why but instead of 254 i put 255 and now is working fine, u can close Issues if u want and thanks again <3

**Comment by grzybeek** [comment]
> instead of 254 i put 255 and now is working fine

Hm, maybe this value is used.. I thought it's not, can you try value 14 or 20 in your free time to see if it crashes as well?

**Comment by hAKIZOR** [comment]
> > instead of 254 i put 255 and now is working fine
> 
> Hm, maybe this value is used.. I thought it's not, can you try value 14 or 20 in your free time to see if it crashes as well?

just one think... Should i make for male 14 and female 20? or they can be equal?

**Comment by hAKIZOR** [comment]
ok with 14 it work ;D
