### ISSUE TITLE
YMTEditor was able to open and edit a YMT but not save the modified YMT

### ISSUE THREAD

**Issue by nayoshi** [grzybeek/YMTEditor#9]
Hey I am trying to add new slots for jbib to a clothing pack I purchased. I exported it and it exported but it says that there was an issue when saying. I added 3 new jbib but not sure what i did incorrectly. 

Here's the ymt file.
[LINK](https://drive.google.com/file/d/16LCLmYS6IAT8rqyJ7ygk0dwiRouu2HBc/view?usp=sharing)

Feel free to let me know if I did anything wrong. It seems that I wasnt able to recreate the file either because mouth, left hand, right hand, etc are disabled. Is there a way to enable those too?

**Comment by grzybeek** [comment]
Answered already on discord DM, but if anyone finds this issue, that's a response:

Disabled props are not used by the game anyway, they are not working, so there is no point for them being enabled. Error at saving is probably fixed already on my PC, code is not pushed yet and probably will be pushed around january.
